---
- hosts: debian
  become: true
  tasks:
    - name: install dependencies
      apt:
        name: "{{item}}"
        state: present
        update_cache: yes
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common
    - name: add dbeaver repository to apt
      apt_repository:
        repo: deb https://dbeaver.io/debs/dbeaver-ce /
        state: present
    - name: install dbeaver
      apt:
        name: "{{item}}"
        state: latest
        update_cache: yes
      loop:
        - dbeaver-ce